Exclude:
  # disable gems
  - /faker/ # TODO: fork gem to add missing keys
  - /simple_form/

  # disable default translations
  - /helpers.page_entries_info/
  - /multibyte/

  # disable special cases
  - /i18n.transliterate.rule/ # transliteration language rules
  - /time.formats.us/ # american time format only present in en-US locale

  # TODO: update the locale files de, en, es
  - /errors/
  - /datetime/
  - /date/
  - /number/
