inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "db/**/schema.rb"
    - "app/controllers/admin/*"
    - "app/dashboards/*"

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
