inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "db/**/schema.rb"

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
