inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - "*.ru"
    - "bin/*"
    - "db/**/*.rb"
    - "config/**/*.rb"
    - "app/controllers/admin/*"
    - "app/controllers/super_admin/*"
    - "app/dashboards/*"
    - "lib/tasks/*"
    - "vendor/**/*"

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "script/**/*"
    - "spec/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"
    - ".*"
