Style/ConditionalAssignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 80

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Bundler/OrderedGems:
  Enabled: false
