inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/*"
    - "db/**/schema.rb"
    - "app/controllers/admin/*"
    - "app/dashboards/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/FrozenStringLiteralComment:
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "db/**/*"
    - "lib/**/*"
    - "script/**/*"
    - "spec/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"
    - ".*"

