script: "bundle exec rake"
bundler_args: "--without development production"
language: ruby
rvm:
  - 2.0.0-p247
branches:
  only:
    - master
before_script:
  - psql -c 'create database onruby_test;' -U postgres
