script: "bundle exec rake"
bundler_args: "--without development production"
language: ruby
rvm:
  - 2.1.0
branches:
  only:
    - master
before_script:
  - psql -c 'create database onruby_test;' -U postgres
