sudo: false
notifications:
  email: false
language: ruby
rvm:
  - 2.6.4
addons:
  postgresql: "9.4"
cache: bundler
bundler_args: "--without development production"
before_script: "script/ci/setup"
script: "script/ci/run"
