Event:
  fields:
    default: id, name, date, user, published
    form: user, location, name, date, description, published
  order_by: -created_at
  search: name, description
  actions:
    edit: publish
  application: CRUD
