# Use the README file as a reference to customize settings.

User:
  fields:
    default: to_label
    form: 
  relationships: authorizations, participants, participations, materials, topics, likes, events
  application: Application
