defaults: &defaults
  email: "hamburg@onruby.de"
  host: "hamburg.onruby.de"
  twitter: "<%= Rails.env.development? ? 'youmouth' : 'hamburgsync' %>"
  usergroup_email: "<%= Rails.env.production? ? 'rubyonrails-ug@headflash.com' : 'phoet@gmx.de' %>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
