defaults: &defaults
  email: "hamburg@onruby.de"
  host: "hamburg.onruby.de"
  twitter: "<%= Rails.env.development? ? "youmouth" : "hamburgsync" %>"
  usergroup_email: "phoet@gmx.de"
  usergroup_email_real: "rubyonrails-ug@headflash.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
