development: &default
  adapter: postgresql
  database: onruby_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV["POSTGRES_PORT_5432_TCP_ADDR"] || 'localhost' %>
  port: <%= ENV["POSTGRES_PORT_5432_TCP_PORT"] || 5432 %>

test:
  <<: *default
  database: onruby_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  encoding: utf8
