development: &default
  adapter: postgresql
  database: onruby_development
  min_messages: WARNING
  pool: 5
  username: postgres
  host: <%= ENV['ONRUBY_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['ONRUBY_DB_1_PORT_5432_TCP_PORT'] %>

test:
  <<: *default
  database: onruby_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  encoding: utf8
