development:
  adapter: postgresql
  database: onruby_development
  username: postgres
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: onruby_test
  username: postgres
  host: localhost
  encoding: utf8
