---
- !ruby/struct:Usergroup
  label_id: "hamburg"
  email: "hamburg@onruby.de"
  host: "hamburg.onruby.de"
  twitter: "hamburgsync"
  usergroup_email: "rubyonrails-ug@headflash.com"
  organizers: ['halfbyte', 'ralph', 'phoet', 'rubiii']
  location:
    zoom: 14
    lat: 53.56544
    long: 9.95947
- !ruby/struct:Usergroup
  label_id: "cologne"
  location:
    zoom: 13
    lat: 50.941231
    long: 6.957092
